name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Generates the snake with different colors
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Pletea-Marinescu-Valentin
          # Use the dark version with custom colors for better visibility
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          # Add a gif output as well
          gif_out_path: dist/github-contribution-grid-snake.gif

      # Push the changes
      - name: Push changes to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
